version: '3.8'

services:
  albumapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DISCOGS_TOKEN=${DISCOGS_TOKEN}
      - GIN_MODE=debug
    volumes:
      - ./views:/app/views
    restart: unless-stopped
    networks:
      - album-network

networks:
  album-network:
    driver: bridge 